#
# PROGRAM:    assign2
# PROGRAMMER: your name
# LOGON ID:   your z-id
# DATE DUE:   due date of program
#

# Compiler variables
CCFLAGS = -w -Wall -std=c++11

assign8: assign8.o 
	g++ $(CCFLAGS) -o assign8 assign8.o 

clean:
	rm *.o assign8
